export * from './ping.controller';
export * from './saludo.controller';
export * from './hoja-de-vida-persona.controller';
export * from './persona-hoja-de-vida.controller';
export * from './foto-persona.controller';
export * from './foto-hoja-de-vida.controller';
export * from './persona.controller';
export * from './hoja-de-vida.controller';
export * from './foto.controller';
